# Generated by Django 5.0.7 on 2024-08-02 19:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inbox', '0002_alter_conversation_options_alter_message_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='conversation',
            name='is_seen',
            field=models.BooleanField(default=False),
        ),
    ]
